/* Edit the cycles object to change clues, answers, or locations. Coordinates are percentages of each image. */
const cycles = {
  carbon: {
    title: 'Carbon', image: 'assets/Ccycle.png', alt: 'Carbon landscape with forest, wildlife, volcano, factory, ocean, and underground material.',
    summary: 'Carbon moves between air, living things, soil, and water. A process can change its molecular form or simply move it.',
    locations: [
      {id:'air',label:'Atmosphere',x:56,y:17}, {id:'plant',label:'Forest / producer',x:80,y:48},
      {id:'animal',label:'Wildlife / consumer',x:92,y:60}, {id:'soil',label:'Soil / dead matter',x:70,y:72},
      {id:'water',label:'Ocean',x:17,y:69}
    ],
    forms: [
      {id:'co2',label:'CO₂ gas'}, {id:'glucose',label:'Glucose'}, {id:'tissue',label:'Carbon in animal tissue'},
      {id:'dead',label:'Dead organic matter'}, {id:'dissolved',label:'Dissolved CO₂'}
    ],
    clues: [
      {title:'A gas in the air',text:'A gas in the air has one carbon atom and two oxygen atoms. Which form is it, and where does it belong?',form:'co2',place:'air',reveal:'Photosynthesis can move its carbon from air into a producer. Imagine an arrow from atmosphere to forest.',question:'Which Lewis structure represents this gas?',answers:['O=C=O, with two double bonds','O–C–O, with only single bonds','C–O–O, with two single bonds'],correct:0,explain:'CO₂ has two C=O double bonds; each oxygen also has two lone pairs.'},
      {title:'A sugar made by a tree',text:'A tree uses light energy to build a six-carbon sugar from matter it took in. Find the form and its reservoir.',form:'glucose',place:'plant',reveal:'Photosynthesis incorporates atmospheric CO₂ carbon into sugars in the producer.',question:'Were the carbon atoms created inside the tree?',answers:['Yes, light energy creates carbon atoms','No, the atoms came from matter the tree took in','Yes, but only during photosynthesis'],correct:1,explain:'Photosynthesis rearranges existing atoms; it does not create carbon.'},
      {title:'A grazing animal',text:'A grazing animal eats a plant and incorporates some of that carbon into its body. Find the form and reservoir.',form:'tissue',place:'animal',reveal:'Consumption transfers organic carbon from producer to consumer.',question:'Does eating a plant itself mean the same thing as cellular respiration?',answers:['Yes, both are the same chemical reaction','No, eating transfers matter; respiration transforms organic molecules','Yes, because both require oxygen'],correct:1,explain:'Eating transfers material. Cellular respiration is a set of metabolic reactions.'},
      {title:'After death',text:'An organism dies, leaving carbon-rich remains in the ground. Find the form and location.',form:'dead',place:'soil',reveal:'Death and waste transfer organic carbon to soil, where decomposers can use it.',question:'Can living microbes metabolize this material after the original organism dies?',answers:['Yes, microbes can break down the remains','No, all chemical reactions stop at death','Only if the dead organism restarts metabolism'],correct:0,explain:'The dead organism has ceased its own metabolism; living decomposers can metabolize its remains.'},
      {title:'Into surface water',text:'Some of the gas found in air enters surface water and remains dissolved there. Find the form and destination.',form:'dissolved',place:'water',reveal:'Dissolution moves CO₂ from air into the ocean. Dissolved CO₂ can also take part in further reactions in water.',question:'In this clue, did CO₂ become a different molecule simply by entering the water?',answers:['Yes, every dissolved gas changes element','No, it can remain CO₂ while dissolved','Yes, it became glucose'],correct:1,explain:'The clue follows CO₂ that remains CO₂ as it enters the water.'}
    ]
  },
  nitrogen: {
    title:'Nitrogen',image:'assets/Ncycle.jpg',alt:'Nitrogen landscape with air, trees, soil, cattle, storm, river, and farm.',
    summary:'Nitrogen can be abundant in air while plants still need usable dissolved nitrogen compounds. Living microbes help change its form.',
    locations:[
      {id:'air',label:'Atmosphere',x:39,y:15},{id:'microbes',label:'Soil microbes',x:24,y:69},
      {id:'soilwater',label:'Soil water',x:42,y:73},{id:'plant',label:'Plants',x:17,y:52},
      {id:'animal',label:'Wildlife / humans',x:53,y:48}
    ],
    forms:[
      {id:'n2',label:'N₂ gas'},{id:'nh3',label:'NH₃ (ammonia)'},{id:'nh4',label:'NH₄⁺ (ammonium)'},
      {id:'amino',label:'N in amino acids'},{id:'protein',label:'N in animal protein'}
    ],
    clues:[
      {title:'A strong bond',text:'Two identical nitrogen atoms form a gas with a strong triple covalent bond. Find the molecule and its reservoir.',form:'n2',place:'air',reveal:'Nitrogen fixation by certain microbes can transform some atmospheric N₂ into ammonia in the soil.',question:'What bond joins the two N atoms?',answers:['A triple nonpolar covalent bond','A single ionic bond','A double polar covalent bond'],correct:0,explain:'Identical N atoms share three electron pairs in N₂.'},
      {title:'A microbial product',text:'Certain living soil microbes make a small compound with one N bonded to three H atoms. Find it and place it near the microbes.',form:'nh3',place:'microbes',reveal:'Nitrogen fixation changes N₂ into ammonia (NH₃), breaking the strong N≡N bond and making new bonds.',question:'What changed during fixation?',answers:['The nitrogen element became phosphorus','The atoms were rearranged into a different compound','New nitrogen atoms were created'],correct:1,explain:'Chemical reactions rearrange atoms and bonds without changing elemental identity.'},
      {title:'A charged form in water',text:'In moist soil, an N-containing compound gains H⁺ and becomes a positively charged ion. Find the form and reservoir.',form:'nh4',place:'soilwater',reveal:'Ammonia can gain a proton in water to become ammonium (NH₄⁺).',question:'Why does this ion usually need a transport protein to enter a plant cell?',answers:['Its charge makes passage through the hydrophobic membrane interior difficult','It is larger than the whole plant','It has no nitrogen atoms'],correct:0,explain:'The charged ion does not readily cross the membrane’s hydrophobic interior.'},
      {title:'Plant building blocks',text:'A plant takes up dissolved N and builds it into the monomers used to make proteins. Find the form and organism.',form:'amino',place:'plant',reveal:'Uptake and synthesis move nitrogen from soil water into plant amino acids.',question:'Why does the plant acquire this nitrogen?',answers:['Mainly to use nitrogen as a source of calories','To build amino acids and other essential molecules','To turn nitrogen atoms into oxygen'],correct:1,explain:'Nitrogen is a structural nutrient for amino acids and nucleotides.'},
      {title:'A consumer’s protein',text:'An animal eats the plant and uses some of its N to build proteins in its own body. Find the form and reservoir.',form:'protein',place:'animal',reveal:'Consumption transfers organic nitrogen from plant to animal.',question:'Was that nitrogen atom created by the animal?',answers:['Yes, when protein was synthesized','No, it was transferred and rearranged','Yes, during digestion'],correct:1,explain:'The nitrogen atom persists as molecules and organisms change.'}
    ]
  },
  phosphorus: {
    title:'Phosphorus',image:'assets/Pcycle.jpg',alt:'Phosphorus landscape with phosphate rock mine, fields, cattle, soil, stream, lake, and fish.',
    summary:'Phosphorus often moves from rocks into soil and water, then into organisms. It has no major atmospheric reservoir in this simplified cycle.',
    locations:[
      {id:'rock',label:'Rock / lithosphere',x:19,y:37},{id:'soilwater',label:'Soil water',x:35,y:67},
      {id:'plant',label:'Crops / plants',x:79,y:48},{id:'animal',label:'Wildlife / humans',x:47,y:46},
      {id:'lake',label:'Lake water',x:60,y:70}
    ],
    forms:[
      {id:'rockp',label:'P in phosphate rock'},{id:'soilp',label:'Phosphate ion in soil water'},
      {id:'lipid',label:'P in phospholipid'},{id:'animalp',label:'P in animal tissue'},
      {id:'lakep',label:'Phosphate ion in lake'}
    ],
    clues:[
      {title:'Stored in rock',text:'Some phosphorus is locked in a solid mineral on a mountainside. Find its form and reservoir.',form:'rockp',place:'rock',reveal:'Weathering releases some phosphate from rock toward soil water.',question:'What is the rock in this example?',answers:['A reservoir that stores phosphorus','A chemical reaction that creates P atoms','A membrane protein'],correct:0,explain:'A reservoir is a place where matter is stored.'},
      {title:'Released into soil',text:'Rain and the breakdown of rock release P as a dissolved, negatively charged ion in soil water. Find its form and reservoir.',form:'soilp',place:'soilwater',reveal:'Weathering transfers phosphorus from rock to soil water as phosphate.',question:'Would this charged ion easily cross a cell membrane’s hydrophobic interior unaided?',answers:['Yes, charge makes it dissolve in lipids','No, it generally needs help from transport proteins','Yes, it can pass through any membrane'],correct:1,explain:'Phosphate is charged and generally requires a membrane transport pathway.'},
      {title:'Part of a membrane',text:'A plant uses P in a molecule with a water-loving head and water-avoiding tails. Find the form and organism.',form:'lipid',place:'plant',reveal:'Plants take up phosphate and synthesize phospholipids, which are part of cell membranes.',question:'How do phospholipids generally orient in a bilayer?',answers:['Heads face water; tails point inward away from water','Tails face water; heads point inward','Heads and tails all face the same direction'],correct:0,explain:'Hydrophilic heads contact water on both sides; hydrophobic tails cluster inside.'},
      {title:'Into an animal',text:'An animal eats plant tissue and incorporates its phosphorus into its own body. Find the form and reservoir.',form:'animalp',place:'animal',reveal:'Consumption transfers phosphorus from producer to consumer.',question:'Did the P atom become a different element?',answers:['Yes, it became carbon','No, its chemical surroundings can change while P remains P','Yes, eating creates new elements'],correct:1,explain:'Changing molecules does not change an atom’s elemental identity.'},
      {title:'Into the lake',text:'Rain carries some dissolved P away from farmland into a lake. Find the form and destination.',form:'lakep',place:'lake',reveal:'Runoff transports dissolved phosphate from land to water.',question:'What could a large added phosphate supply promote?',answers:['Algal growth, if phosphate limits it','Immediate disappearance of every aquatic organism','Conversion of phosphorus into nitrogen'],correct:0,explain:'Extra nutrients can stimulate algal growth under suitable conditions.'}
    ]
  }
};

const $ = id => document.getElementById(id);
let cycleKey=null, order=[], index=0, selected=null, phase='choose', placements=[], attempts=0;
function shuffle(a){const copy=[...a];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function current(){return cycles[cycleKey].clues[order[index]]}
function showChooser(){cycleKey=null;$('game').hidden=true;$('chooser').hidden=false;$('change-cycle').hidden=true;window.scrollTo({top:0,behavior:'smooth'})}
function start(key){cycleKey=key;order=shuffle(cycles[key].clues.map((_,i)=>i));index=0;placements=[];attempts=0;$('chooser').hidden=true;$('game').hidden=false;$('complete').hidden=true;$('change-cycle').hidden=false;$('cycle-name').textContent=cycles[key].title+' cycle';$('scene-image').src=cycles[key].image;$('scene-image').alt=cycles[key].alt;renderHotspots();renderClue();window.scrollTo({top:0,behavior:'smooth'})}
function renderHotspots(){const root=$('hotspots');root.replaceChildren();for(const loc of cycles[cycleKey].locations){const b=document.createElement('button');b.className='hotspot';b.type='button';b.style.left=loc.x+'%';b.style.top=loc.y+'%';b.textContent=loc.label;b.setAttribute('aria-label','Place selected form in '+loc.label);b.dataset.location=loc.id;b.onclick=()=>tryPlace(loc.id,b);b.ondragover=e=>{e.preventDefault();e.dataTransfer.dropEffect='move'};b.ondrop=e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(cycles[cycleKey].forms.some(f=>f.id===id)){selected=id;markSelected();tryPlace(loc.id,b)}};root.append(b)}drawPlacements()}
function drawPlacements(){document.querySelectorAll('.placed').forEach(e=>e.remove());const root=$('hotspots');for(const p of placements){const loc=cycles[cycleKey].locations.find(l=>l.id===p.place);const form=cycles[cycleKey].forms.find(f=>f.id===p.form);const d=document.createElement('span');d.className='placed';d.style.left=Math.min(90,loc.x+7)+'%';d.style.top=Math.min(89,loc.y+4)+'%';d.textContent=form.label;root.append(d)}}
function renderClue(){const data=cycles[cycleKey],clue=current();selected=null;phase='choose';$('progress-text').textContent=`Clue ${index+1} of ${data.clues.length}`;$('progress-dots').replaceChildren();data.clues.forEach((_,i)=>{const d=document.createElement('i');if(i<index)d.className='done';$('progress-dots').append(d)});$('card-number').textContent='Card '+(index+1);$('clue-title').textContent=clue.title;$('clue-text').textContent=clue.text;$('form-stage').hidden=false;$('reveal').hidden=true;$('next-button').hidden=true;$('feedback').textContent='';$('feedback').className='feedback';$('bonus-feedback').textContent='';$('form-hint').textContent='Then choose its location on the image.';const root=$('form-options');root.replaceChildren();shuffle(data.forms).forEach(f=>{const b=document.createElement('button');b.className='form-option';b.type='button';b.textContent=f.label;b.dataset.form=f.id;b.draggable=true;b.onclick=()=>chooseForm(f.id);b.ondragstart=e=>{e.dataTransfer.setData('text/plain',f.id);e.dataTransfer.effectAllowed='move';chooseForm(f.id)};root.append(b)});renderHotspots()}
function markSelected(){document.querySelectorAll('.form-option').forEach(b=>{b.classList.toggle('selected',b.dataset.form===selected);b.setAttribute('aria-pressed',String(b.dataset.form===selected))})}
function chooseForm(id){if(phase!=='choose')return;selected=id;markSelected();$('feedback').textContent='Form selected. Now choose a location on the diagram.';$('feedback').className='feedback good'}
function tryPlace(locId,button){if(phase!=='choose')return;if(!selected){$('feedback').textContent='Choose a form first, then select a location.';$('feedback').className='feedback';return}const clue=current();if(selected!==clue.form||locId!==clue.place){attempts++;button.classList.add('wrong');setTimeout(()=>button.classList.remove('wrong'),700);$('feedback').textContent=selected!==clue.form?'That form does not fit this clue. Try another.':'That form fits, but this location does not. Try another reservoir.';$('feedback').className='feedback';return}phase='bonus';button.classList.add('correct');placements.push({form:clue.form,place:clue.place});drawPlacements();$('feedback').textContent='Correct form and reservoir! Turn over the clue card.';$('feedback').className='feedback good';$('form-stage').hidden=true;$('reveal').hidden=false;$('reveal-text').textContent=clue.reveal;$('bonus-question').textContent=clue.question;const root=$('bonus-options');root.replaceChildren();clue.answers.forEach((a,i)=>{const b=document.createElement('button');b.type='button';b.className='bonus-option';b.textContent=a;b.onclick=()=>answerBonus(i);root.append(b)})}
function answerBonus(i){if(phase!=='bonus')return;const clue=current();phase='answered';document.querySelectorAll('.bonus-option').forEach((b,n)=>{b.disabled=true;if(n===clue.correct)b.classList.add('correct');else if(n===i)b.classList.add('incorrect')});$('bonus-feedback').textContent=(i===clue.correct?'Correct. ':'The highlighted answer is correct. ')+clue.explain;$('next-button').hidden=false;$('next-button').textContent=index===cycles[cycleKey].clues.length-1?'Finish cycle':'Next clue'}
function next(){if(phase!=='answered')return;index++;if(index<cycles[cycleKey].clues.length){renderClue();return}$('complete').hidden=false;$('complete-summary').textContent=cycles[cycleKey].summary+' You placed all five forms. '+(attempts?'You retried '+attempts+' placement'+(attempts===1?'':'s')+' along the way.':'');$('progress-text').textContent='5 of 5 complete';$('progress-dots').querySelectorAll('i').forEach(d=>d.className='done');$('form-stage').hidden=true;$('reveal').hidden=true;$('feedback').textContent='';$('complete').scrollIntoView({behavior:'smooth',block:'nearest'})}
for(const [key,data] of Object.entries(cycles)){const b=document.createElement('button');b.className='cycle-choice';b.type='button';b.innerHTML=`<img src="${data.image}" alt=""><span><strong>${data.title}</strong><small>Five clues · form, reservoir, and process</small></span>`;b.onclick=()=>start(key);$('cycle-choices').append(b)}
$('change-cycle').onclick=showChooser;$('next-button').onclick=next;$('restart-cycle').onclick=()=>start(cycleKey);$('pick-cycle').onclick=showChooser;
